/**
 * MaterialCommunityIcons names for reliable rendering on Android (no CDN).
 * Keys match AppIcon `name` props used across the app.
 */
export const ICON_MCI_MAP = {
  home: 'home',
  'home-variant': 'home',
  dashboard: 'view-dashboard',
  menu: 'menu',
  search: 'magnify',
  settings: 'cog',
  'arrow-back': 'arrow-left',
  'chevron-right': 'chevron-right',
  'chevron-left': 'chevron-left',
  forward: 'chevron-right',
  back: 'arrow-left',
  close: 'close',
  add: 'plus',
  plus: 'plus',
  minus: 'minus',

  account: 'account',
  'account-outline': 'account-outline',
  'account-circle': 'account-circle',
  'account-circle-outline': 'account-circle-outline',
  profile: 'account',
  'user-settings': 'account-cog-outline',
  at: 'at',
  users: 'account-group',
  'account-lock': 'account-lock',
  pencil: 'pencil',
  edit: 'pencil',
  logout: 'logout',
  'log-out': 'logout',

  whatsapp: 'chat',
  telegram: 'send',
  instagram: 'instagram',
  'instagram-new': 'instagram',
  send: 'send',
  'message-text': 'message-text',
  email: 'email',
  mail: 'email',

  headset: 'headset',
  support: 'headset',
  'help-circle': 'help-circle',
  help: 'help-circle',
  information: 'information',
  info: 'information',
  'alert-circle': 'alert-circle',
  'alert-circle-outline': 'alert-circle-outline',
  'close-circle': 'close-circle',
  'information-circle': 'information',
  warning: 'alert',
  'currency-inr': 'currency-inr',
  rupee: 'currency-inr',

  wallet: 'wallet-outline',
  'wallet-plus-outline': 'wallet-plus-outline',
  'wallet-plus': 'wallet-plus',
  'cash-multiple': 'cash-multiple',
  'cash-alert': 'cash-alert',
  'circle-multiple': 'circle-multiple',
  coins: 'circle-multiple',

  upcoming: 'clock-outline',
  ongoing: 'broadcast',
  completed: 'check-circle',

  trophy: 'trophy',
  'trophy-outline': 'trophy-outline',
  'trophy-alert': 'trophy',
  'trophy-variant': 'trophy',
  'gamepad-variant': 'gamepad-variant',
  'game-controller': 'gamepad-variant',
  podium: 'podium',
  'podium-gold': 'podium-gold',
  history: 'history',
  'clock-outline': 'clock-outline',
  clock: 'clock',
  broadcast: 'broadcast',
  'live-tv': 'television-play',
  'youtube-live': 'youtube',
  'check-circle-outline': 'check-circle-outline',
  'check-circle': 'check-circle',
  checkmark: 'check',
  'check-decagram': 'check-decagram',
  'shield-check': 'shield-check',
  'shield-crown': 'shield-crown',

  'share-variant': 'share-variant',
  share: 'share',
  download: 'download',
  upload: 'upload',
  delete: 'delete',
  trash: 'delete',
  'trash-outline': 'delete-outline',
  copy: 'content-copy',
  refresh: 'refresh',
  filter: 'filter',
  sort: 'sort',

  bell: 'bell',
  notifications: 'bell',
  bullhorn: 'bullhorn',
  'bullhorn-outline': 'bullhorn-outline',
  megaphone: 'bullhorn',
  advertising: 'billboard',
  'view-carousel': 'view-carousel',
  image: 'image',
  'image-off-outline': 'image-off-outline',
  video: 'video',
  play: 'play',

  'chart-bar': 'chart-bar',
  'chart-line': 'chart-line',
  'chart-timeline-variant': 'chart-timeline-variant',
  percentage: 'percent',
  analytics: 'chart-line',
  statistics: 'chart-bar',

  'file-document': 'file-document',
  document: 'file-document',
  'shield-check-outline': 'shield-check-outline',

  'cellphone-cog': 'cellphone-cog',
  'cash-register': 'cash-register',
  ticket: 'ticket',
  'ticket-outline': 'ticket-outline',
  ban: 'cancel',
  'checkmark-circle': 'check-circle',
  'checkmark-circle-outline': 'check-circle-outline',
  star: 'star',
  heart: 'heart',
  eye: 'eye',
  'eye-off': 'eye-off',
  lock: 'lock',
  'lock-outline': 'lock-outline',
  'lock-check-outline': 'lock-check',
  unlock: 'lock-open',
  'gift-outline': 'gift-outline',
  gift: 'gift',
  calendar: 'calendar',
  location: 'map-marker',
  link: 'link',
  'open-outline': 'open-in-new',
  'external-link': 'open-in-new',
  facebook: 'facebook',
  twitter: 'twitter',
  'chatbubbles-outline': 'chat',
  chat: 'chat',
};

export function resolveMciIcon(name) {
  if (!name) return 'help-circle';
  const key = String(name).trim();
  if (ICON_MCI_MAP[key]) return ICON_MCI_MAP[key];
  if (key.includes('-')) return key;
  return 'help-circle';
}
