const express = require('express');
const User = require('../models/User');
const Tournament = require('../models/Tournament');
require('../models/DailyAutoMatch');
const TournamentParticipant = require('../models/TournamentParticipant');
const Team = require('../models/Team');
const TeamMember = require('../models/TeamMember');
const PrizeDistribution = require('../models/PrizeDistribution');
const BattleRoyaleResult = require('../models/BattleRoyaleResult');
const BattleRoyaleTeamResult = require('../models/BattleRoyaleTeamResult');
const CustomMatchResult = require('../models/CustomMatchResult');
const WinnerPayout = require('../models/WinnerPayout');
const WalletTransaction = require('../models/WalletTransaction');
const { authMiddleware } = require('../middleware/auth');
const lifecycle = require('../services/tournamentLifecycle');
const winnerPayoutService = require('../services/winnerPayoutService');
const brReward = require('../services/battleRoyaleRewardService');
const {
  notifyMatchLive,
  notifyMatchCompleted,
  notifyResultsPublished,
  notifyTournamentJoined,
} = require('../services/tournamentPushEvents');

const router = express.Router();

const MAX_BONUS_ENTRY_PERCENT = 0.2;

const getEntryPaymentSplit = (user, entryFee) => {
  const fee = Number(entryFee) || 0;
  const bonusBalance = Number(user?.wallet?.bonusBalance) || 0;
  const maxBonusAllowed = Math.floor(fee * MAX_BONUS_ENTRY_PERCENT);
  const bonusUsed = Math.min(bonusBalance, maxBonusAllowed);
  const realMoneyRequired = Math.max(fee - bonusUsed, 0);
  return { bonusUsed, realMoneyRequired, maxBonusAllowed };
};

async function requireAdmin(req, res) {
  const admin = await User.findById(req.userId);
  if (!admin) {
    res.status(401).json({ error: 'Session expired. Please sign in again.' });
    return null;
  }
  if (admin.role !== 'admin') {
    res.status(403).json({ error: 'Admin access required' });
    return null;
  }
  return admin;
}

function formatListItem(tournament, joinStats) {
  const status = lifecycle.getEffectiveStatus(tournament);
  const type = lifecycle.getTournamentType(tournament);
  const structure = lifecycle.getMatchStructure(tournament);
  const charge = lifecycle.resolveEntryCharge(tournament);
  const { joinedCount, capacity, unit, isFull, usesTeams } = joinStats;
  const prizePool = Math.max(0, Number(tournament.prizePool) || 0);
  const perKillRaw = Math.max(0, Number(tournament.perKill) || 0);
  const showPerKill = Boolean(structure.hasKillRewards) && perKillRaw > 0;
  return {
    _id: tournament._id,
    name: tournament.name,
    tournamentType: type,
    category: tournament.category,
    matchKind: structure.kind,
    matchType: structure.matchTypeName || structure.matchType,
    matchTypeName: structure.matchTypeName || structure.matchType,
    formatLabel: structure.formatLabel,
    playerFormatLabel: structure.playerFormatLabel,
    mode: structure.mode,
    modeLabel: structure.modeLabel,
    hasKillRewards: structure.hasKillRewards,
    entryFee: charge.feePerPlayer,
    entryFeePerPlayer: charge.feePerPlayer,
    feePerPlayer: charge.feePerPlayer,
    playersCharged: charge.playersCharged,
    totalAmount: charge.totalAmount,
    perKill: showPerKill ? perKillRaw : 0,
    showPrizePerKill: showPerKill,
    showPrizePool: prizePool > 0,
    joinedCount,
    capacity,
    joinUnit: unit,
    usesTeams,
    isFull,
    showFullBadge: lifecycle.shouldShowFullBadge(status, isFull),
    fullLabel: type === 'custom_match' ? 'Match Full' : 'Tournament Full',
    status,
    lifecycleStatus: status,
    matchDate: tournament.startDate,
    startDate: tournament.startDate,
    gameMode: tournament.gameMode,
    gameName: tournament.game?.name || null,
    maxParticipants: tournament.maxParticipants,
    maxTeams: tournament.maxTeams,
    prizePool,
    map: tournament.map || '',
    mapName: tournament.map || '',
    bannerImage: tournament.bannerImage || '',
    locked: Boolean(tournament.locked),
    resultsPublished: lifecycle.areResultsPublished(tournament),
    isAutoGenerated: Boolean(tournament.isAutoGenerated),
    autoMatchId: tournament.autoMatchId?._id || tournament.autoMatchId || null,
    autoMatchName: tournament.autoMatchId?.name || '',
    autoMatchDisplayId: tournament.autoMatchId?.displayId || '',
    autoMatchNumber: tournament.autoMatchId?.autoMatchNumber || null,
    generatedDate: tournament.generatedDate || '',
  };
}

function escapeRegex(value) {
  return String(value || '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function listStatusMatch(status) {
  const s = String(status || '').trim();
  if (!s) return null;
  if (s === 'upcoming') return { $in: ['upcoming', 'incoming'] };
  if (s === 'live' || s === 'ongoing') return { $in: ['ongoing', 'live'] };
  if (s === 'completed') return { $in: ['completed', 'result_published'] };
  return s;
}

// ——— Admin list ———
router.get('/admin/list', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const page = req.query.page != null && req.query.page !== ''
      ? Math.max(1, Number(req.query.page) || 1)
      : null;
    const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20));
    const search = String(req.query.search || '').trim();
    const status = listStatusMatch(req.query.status);
    const category = String(req.query.category || '').trim();
    const mode = String(req.query.mode || '').trim();
    const filter = {};

    if (search) filter.name = new RegExp(escapeRegex(search), 'i');
    if (status) filter.$or = [{ lifecycleStatus: status }, { status }];
    if (category === 'custom' || category === 'custom_match') {
      filter.category = { $in: ['custom', 'custom_match'] };
    } else if (category) {
      filter.category = category;
    }
    if (['solo', 'duo', 'squad'].includes(mode)) filter.mode = mode;
    if (req.query.from || req.query.to) {
      filter.startDate = {};
      if (req.query.from) filter.startDate.$gte = new Date(req.query.from);
      if (req.query.to) {
        const end = new Date(req.query.to);
        end.setHours(23, 59, 59, 999);
        filter.startDate.$lte = end;
      }
    }
    if (req.query.entryMin !== undefined && req.query.entryMin !== '') {
      filter.entryFee = { ...(filter.entryFee || {}), $gte: Number(req.query.entryMin) || 0 };
    }
    if (req.query.entryMax !== undefined && req.query.entryMax !== '') {
      filter.entryFee = { ...(filter.entryFee || {}), $lte: Number(req.query.entryMax) || 0 };
    }

    let find = Tournament.find(filter)
      .populate('game', 'name')
      .populate('gameMode', 'name')
      .populate('matchType')
      .populate('autoMatchId', 'name displayId autoMatchNumber')
      .sort({ createdAt: -1 });
    let total = 0;
    if (page) {
      total = await Tournament.countDocuments(filter);
      find = find.skip((page - 1) * limit).limit(limit);
    }

    const tournaments = await find.lean();
    const list = await Promise.all(
      tournaments.map(async (t) => {
        const doc = await Tournament.findById(t._id);
        if (doc && lifecycle.ensureLifecycleSynced(doc)) {
          await doc.save();
          Object.assign(t, {
            status: doc.status,
            lifecycleStatus: doc.lifecycleStatus,
            locked: doc.locked,
            resultsPublished: doc.resultsPublished,
          });
        }
        const joinStats = await lifecycle.getJoinStats(t._id, t);
        return formatListItem(t, joinStats);
      })
    );

    if (!page) {
      const STATUS_ORDER = ['draft', 'upcoming', 'incoming', 'ongoing', 'completed', 'cancelled'];
      list.sort((a, b) => {
        const ai = STATUS_ORDER.indexOf(a.status);
        const bi = STATUS_ORDER.indexOf(b.status);
        if (ai !== bi) return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
        return new Date(b.matchDate) - new Date(a.matchDate);
      });
      return res.json(list);
    }

    res.json({ items: list, total, page, limit, pages: Math.ceil(total / limit) || 1 });
  } catch (error) {
    console.error('admin list:', error);
    res.status(500).json({ error: 'Failed to fetch tournaments' });
  }
});

// Global payout list — MUST be before /admin/:id
router.get('/admin/payouts', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    const data = await winnerPayoutService.listPayoutsAdmin({
      status: req.query.status,
      page: Number(req.query.page) || 1,
      limit: Number(req.query.limit) || 30,
      search: req.query.search,
    });
    res.json(data);
  } catch (e) {
    res.status(500).json({ error: e.message || 'Failed to list payouts' });
  }
});

// ——— Single tournament (admin) ———
router.get('/admin/:id', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id)
      .populate('game', 'name image')
      .populate('gameMode', 'name image')
      .populate('matchType')
      .populate('autoMatchId', 'name displayId autoMatchNumber isActive');
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const joinStats = await lifecycle.getJoinStats(tournament._id, tournament);
    const prizeDistribution = await PrizeDistribution.findOne({ tournamentId: tournament._id }).lean();
    const status = lifecycle.getEffectiveStatus(tournament);

    let participants = [];
    let teams = [];
    const structure = lifecycle.getMatchStructure(tournament);
    const charge = lifecycle.resolveEntryCharge(tournament);

    if (structure.usesTeamRegistration) {
      teams = await Team.find({ tournamentId: tournament._id, status: 'registered' })
        .populate('captainUserId', 'username email')
        .lean();
      const members = await TeamMember.find({ tournamentId: tournament._id })
        .populate('userId', 'username email')
        .lean();
      teams = teams.map((team) => ({
        ...team,
        members: members.filter((m) => String(m.teamId) === String(team._id)),
      }));
    } else {
      participants = await TournamentParticipant.find({
        tournamentId: tournament._id,
        status: { $in: ['joined', 'winner'] },
      })
        .populate('userId', 'username email')
        .sort({ slotNumber: 1 })
        .lean();
    }

    res.json({
      tournament: tournament.toObject(),
      status,
      resultsPublished: lifecycle.areResultsPublished(tournament),
      matchKind: structure.kind,
      matchType: structure.matchType,
      formatLabel: structure.formatLabel,
      playerFormatLabel: structure.playerFormatLabel,
      modeLabel: structure.modeLabel,
      playersPerTeam: structure.playersPerTeam,
      slotUnit: structure.slotUnit,
      entryUnit: structure.entryUnit,
      feePerPlayer: charge.feePerPlayer,
      entryChargeTotal: charge.totalAmount,
      playersCharged: charge.playersCharged,
      teamSetup: structure.usesTeamSides
        ? 'Team A vs Team B'
        : structure.usesTeamRegistration
          ? `${structure.modeLabel} teams`
          : 'Solo — individual slots',
      hasKillRewards: structure.hasKillRewards,
      joinedCount: joinStats.joinedCount,
      capacity: joinStats.capacity,
      joinUnit: joinStats.unit,
      usesTeams: joinStats.usesTeams,
      isFull: joinStats.isFull,
      showFullBadge: lifecycle.shouldShowFullBadge(status, joinStats.isFull),
      prizeDistribution,
      participants,
      teams,
    });
  } catch (error) {
    console.error('admin get:', error);
    res.status(500).json({ error: 'Failed to fetch tournament' });
  }
});

// ——— Prize distribution ———
router.put('/admin/:id/prize-distribution', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const type = lifecycle.getTournamentType(tournament);
    const { rankTiers, winnerPrize, runnerUpPrize } = req.body;

    if (type === 'battle_royale') {
      const v = lifecycle.validateRankTiers(rankTiers);
      if (!v.ok) return res.status(400).json({ error: v.error });
    } else {
      if (Number(winnerPrize) < 0) {
        return res.status(400).json({ error: 'Prize cannot be negative' });
      }
    }

    const doc = await PrizeDistribution.findOneAndUpdate(
      { tournamentId: tournament._id },
      {
        tournamentId: tournament._id,
        tournamentType: type,
        rankTiers: type === 'battle_royale' ? rankTiers : [],
        winnerPrize:
          type === 'custom_match'
            ? Number(winnerPrize) || Number(tournament.prizePool) || 0
            : 0,
        runnerUpPrize: 0,
        updatedAt: new Date(),
      },
      { upsert: true, new: true }
    );

    res.json({ prizeDistribution: doc });
  } catch (error) {
    console.error('prize distribution:', error);
    res.status(500).json({ error: 'Failed to save prize distribution' });
  }
});

router.get('/admin/:id/prize-distribution', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    const doc = await PrizeDistribution.findOne({ tournamentId: req.params.id }).lean();
    res.json(doc || null);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch prize distribution' });
  }
});

// ——— Lifecycle transitions ———
async function transitionStatus(req, res, nextStatus) {
  const tournament = await Tournament.findById(req.params.id);
  if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

  if (lifecycle.ensureLifecycleSynced(tournament)) {
    await tournament.save();
  }

  const check = lifecycle.assertTransition(tournament, nextStatus);
  if (!check.ok) return res.status(400).json({ error: check.error });

  lifecycle.syncLegacyFields(tournament, nextStatus);
  await tournament.save();

  if (nextStatus === 'ongoing') {
    notifyMatchLive(tournament).catch((e) => console.error('live notify:', e.message));
  } else if (nextStatus === 'completed') {
    notifyMatchCompleted(tournament).catch((e) => console.error('complete notify:', e.message));
  }

  res.json({
    message: `Tournament is now ${nextStatus}`,
    tournament,
    status: nextStatus,
    redirectToResultEntry: nextStatus === 'completed',
  });
}

router.post('/admin/:id/publish', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    await transitionStatus(req, res, 'upcoming');
  } catch (e) {
    res.status(500).json({ error: 'Failed to publish tournament' });
  }
});

router.post('/admin/:id/start-match', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    await transitionStatus(req, res, 'ongoing');
  } catch (e) {
    res.status(500).json({ error: 'Failed to start match' });
  }
});

router.post('/admin/:id/complete-match', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    await transitionStatus(req, res, 'completed');
  } catch (e) {
    res.status(500).json({ error: 'Failed to complete match' });
  }
});

router.post('/admin/:id/publish-results', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const status = lifecycle.getEffectiveStatus(tournament);
    if (status !== 'completed') {
      return res.status(400).json({ error: 'Tournament must be completed before publishing results' });
    }
    if (lifecycle.areResultsPublished(tournament)) {
      return res.status(400).json({
        error: 'Results already published — wallet payouts will not run again',
        alreadyPublished: true,
      });
    }

    const isTeamBr =
      lifecycle.isBattleRoyale(tournament) && lifecycle.usesTeamRegistration(tournament);

    if (lifecycle.isBattleRoyale(tournament)) {
      if (isTeamBr) {
        const teamCount = await Team.countDocuments({
          tournamentId: tournament._id,
          status: 'registered',
        });
        const resultCount = await BattleRoyaleTeamResult.countDocuments({
          tournamentId: tournament._id,
        });
        if (teamCount > 0 && resultCount < teamCount) {
          return res.status(400).json({
            error: 'Save placement and kills for every registered team first',
          });
        }
      } else {
        const joinedCount = await lifecycle.getJoinedCount(tournament._id, tournament);
        const resultCount = await BattleRoyaleResult.countDocuments({
          tournamentId: tournament._id,
        });
        if (joinedCount > 0 && resultCount < joinedCount) {
          return res.status(400).json({ error: 'Save results for every joined player first' });
        }
      }
    } else {
      const custom = await CustomMatchResult.findOne({ tournamentId: tournament._id });
      if (!custom) {
        return res.status(400).json({ error: 'Save Clash Squad results first' });
      }
    }

    const marked = lifecycle.markResultsPublished(tournament);
    if (!marked.ok) return res.status(400).json({ error: marked.error });
    await tournament.save();

    // Create WinnerPayout records + optional auto-credit (TEST wallet)
    let payoutSummary = { credited: 0 };
    try {
      if (lifecycle.isBattleRoyale(tournament)) {
        if (isTeamBr) {
          const teamRows = await BattleRoyaleTeamResult.find({
            tournamentId: tournament._id,
          });
          const items = await brReward.buildTeamPayoutItems(tournament, teamRows);
          await winnerPayoutService.ensurePayoutRecords(items);
        } else {
          const brRows = await BattleRoyaleResult.find({ tournamentId: tournament._id });
          await winnerPayoutService.ensurePayoutRecords(
            brReward.buildSoloPayoutItems(tournament, brRows)
          );
        }
      } else {
        const custom = await CustomMatchResult.findOne({ tournamentId: tournament._id });
        if (custom && Number(custom.winnerPrize) > 0) {
          const winnerTeam = await Team.findById(custom.winnerTeamId);
          if (winnerTeam?.captainUserId) {
            await winnerPayoutService.ensurePayoutRecords([
              {
                tournamentId: tournament._id,
                userId: winnerTeam.captainUserId,
                resultId: custom._id,
                resultModel: 'CustomMatchResult',
                amount: Number(custom.winnerPrize) || 0,
                usernameSnapshot: '',
                description: `Clash Squad winner prize — ${tournament.name}`,
              },
            ]);
          }
        }
      }
      payoutSummary = await winnerPayoutService.autoCreditPendingForTournament(tournament._id, {
        tournamentName: tournament.name,
      });

      // Keep legacy prizeCredited flag in sync for custom matches
      if (!lifecycle.isBattleRoyale(tournament)) {
        const paid = await WinnerPayout.countDocuments({
          tournamentId: tournament._id,
          resultModel: 'CustomMatchResult',
          status: 'PAID',
        });
        if (paid > 0) {
          await CustomMatchResult.updateOne(
            { tournamentId: tournament._id },
            { $set: { prizeCredited: true } }
          );
        }
      }
    } catch (payoutErr) {
      console.error('publish-results payout:', payoutErr);
    }

    try {
      const paidPayouts = await WinnerPayout.find({
        tournamentId: tournament._id,
        status: { $in: ['PAID', 'PENDING'] },
        amount: { $gt: 0 },
      }).select('userId amount status');
      const winnerAmounts = {};
      const winnerUserIds = [];
      paidPayouts.forEach((p) => {
        winnerUserIds.push(String(p.userId));
        winnerAmounts[String(p.userId)] = Number(p.amount) || 0;
      });
      await notifyResultsPublished(tournament, { winnerUserIds, winnerAmounts });
    } catch (notifyErr) {
      console.error('results published notify:', notifyErr.message);
    }

    res.json({
      message: 'Results published',
      tournament,
      status: 'completed',
      resultsPublished: true,
      payoutsCredited: payoutSummary.credited || 0,
      autoPaymentEnabled: tournament.autoPaymentEnabled !== false,
      controlWindow: winnerPayoutService.getControlWindow(tournament),
    });
  } catch (e) {
    res.status(500).json({ error: 'Failed to publish results' });
  }
});

// ——— Battle Royale results ———
router.get('/admin/:id/results/battle-royale', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });
    if (!lifecycle.isBattleRoyale(tournament)) {
      return res.status(400).json({ error: 'Not a Battle Royale tournament' });
    }

    const isTeamMode = lifecycle.usesTeamRegistration(tournament);
    const prizeDistribution = await PrizeDistribution.findOne({
      tournamentId: tournament._id,
    }).lean();

    const prizeConfig = {
      first: Number(tournament.prizes?.first) || 0,
      second: Number(tournament.prizes?.second) || 0,
      third: Number(tournament.prizes?.third) || 0,
      perKill: Number(tournament.perKill) || 0,
    };

    if (isTeamMode) {
      const teams = await Team.find({
        tournamentId: tournament._id,
        status: 'registered',
      }).lean();
      const members = await TeamMember.find({ tournamentId: tournament._id })
        .populate('userId', 'username')
        .lean();
      const saved = await BattleRoyaleTeamResult.find({ tournamentId: tournament._id })
        .sort({ position: 1 })
        .lean();

      return res.json({
        mode: tournament.mode,
        isTeamMode: true,
        teams: teams.map((t) => ({
          ...t,
          members: members.filter((m) => String(m.teamId) === String(t._id)),
          players: t.players || [],
        })),
        teamResults: saved,
        participants: [],
        results: [],
        prizeDistribution,
        prizeConfig,
        status: lifecycle.getEffectiveStatus(tournament),
      });
    }

    const participants = await TournamentParticipant.find({
      tournamentId: tournament._id,
      status: { $in: ['joined', 'winner'] },
    })
      .populate('userId', 'username email')
      .sort({ slotNumber: 1 });

    const saved = await BattleRoyaleResult.find({ tournamentId: tournament._id })
      .populate('userId', 'username')
      .sort({ position: 1 });

    res.json({
      mode: tournament.mode,
      isTeamMode: false,
      participants,
      results: saved,
      teams: [],
      teamResults: [],
      prizeDistribution,
      prizeConfig,
      status: lifecycle.getEffectiveStatus(tournament),
    });
  } catch (e) {
    console.error('load BR results:', e);
    res.status(500).json({ error: 'Failed to load result entry data' });
  }
});

router.post('/admin/:id/results/battle-royale', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const { entries } = req.body;
    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });
    if (!lifecycle.isBattleRoyale(tournament)) {
      return res.status(400).json({ error: 'Not a Battle Royale tournament' });
    }

    const status = lifecycle.getEffectiveStatus(tournament);
    if (status !== 'completed') {
      return res.status(400).json({ error: 'Results can only be entered when match is completed' });
    }
    if (lifecycle.areResultsPublished(tournament)) {
      return res.status(400).json({ error: 'Tournament is read-only after results are published' });
    }

    const isTeamMode = lifecycle.usesTeamRegistration(tournament);

    if (isTeamMode) {
      const teams = await Team.find({
        tournamentId: tournament._id,
        status: 'registered',
      }).select('_id');
      const teamIds = teams.map((t) => t._id);

      const validation = lifecycle.validateBattleRoyaleTeamResults(entries, teamIds);
      if (!validation.ok) return res.status(400).json({ error: validation.error });

      if ((entries || []).length !== teamIds.length) {
        return res.status(400).json({
          error: `Every registered team needs a result (${teamIds.length} required)`,
        });
      }

      const enriched = [];
      for (const raw of entries) {
        const out = brReward.enrichTeamEntry(tournament, raw);
        if (!out.ok) return res.status(400).json({ error: out.error });
        enriched.push(out.entry);
      }

      await BattleRoyaleTeamResult.deleteMany({ tournamentId: tournament._id });
      // Clear any leftover solo rows from mode changes
      await BattleRoyaleResult.deleteMany({ tournamentId: tournament._id });

      const docs = await BattleRoyaleTeamResult.insertMany(
        enriched.map((e) => ({
          tournamentId: tournament._id,
          teamId: e.teamId,
          position: e.position,
          teamKills: e.teamKills,
          placementPrize: e.placementPrize,
          killReward: e.killReward,
          totalPrize: e.totalPrize,
          playerKills: e.playerKills || [],
        }))
      );

      return res.json({
        message: 'Battle Royale team results saved',
        isTeamMode: true,
        results: docs,
      });
    }

    const joinedCount = await lifecycle.getJoinedCount(tournament._id, tournament);
    const validation = lifecycle.validateBattleRoyaleResults(entries, joinedCount);
    if (!validation.ok) return res.status(400).json({ error: validation.error });

    const participantUserIds = new Set(
      (
        await TournamentParticipant.find({
          tournamentId: tournament._id,
          status: { $in: ['joined', 'winner'] },
        }).select('userId')
      ).map((p) => String(p.userId))
    );

    const enriched = [];
    for (const e of entries) {
      if (!participantUserIds.has(String(e.userId))) {
        return res.status(400).json({ error: 'All result players must be joined participants' });
      }
      const out = brReward.enrichSoloEntry(tournament, e);
      if (!out.ok) return res.status(400).json({ error: out.error });
      enriched.push(out.entry);
    }

    await BattleRoyaleResult.deleteMany({ tournamentId: tournament._id });
    await BattleRoyaleTeamResult.deleteMany({ tournamentId: tournament._id });

    const docs = await BattleRoyaleResult.insertMany(
      enriched.map((e) => ({
        tournamentId: tournament._id,
        userId: e.userId,
        participantId: e.participantId,
        position: Number(e.position),
        kills: Number(e.kills) || 0,
        prize: Number(e.prize) || 0,
        gamingUsername: e.gamingUsername,
        gamingUID: e.gamingUID,
      }))
    );

    for (const e of enriched) {
      await TournamentParticipant.findOneAndUpdate(
        { tournamentId: tournament._id, userId: e.userId },
        {
          rank: Number(e.position),
          prizeAmount: Number(e.prize) || 0,
          status: Number(e.position) === 1 ? 'winner' : 'joined',
        }
      );
    }

    res.json({ message: 'Battle Royale results saved', isTeamMode: false, results: docs });
  } catch (e) {
    console.error('save BR results:', e);
    res.status(500).json({ error: 'Failed to save results' });
  }
});

// Auto-fill prizes from placement + kill formula (and optional tiers for placement override)
router.post('/admin/:id/results/battle-royale/prize-preview', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const { positions, kills } = req.body;
    const preview = (positions || []).map((rank, idx) => {
      const k = Array.isArray(kills) ? Number(kills[idx]) || 0 : 0;
      const reward = brReward.computeReward(tournament, rank, k);
      return {
        position: rank,
        kills: k,
        placementPrize: reward.placementPrize,
        killReward: reward.killReward,
        prize: reward.totalReward,
      };
    });
    res.json({ preview, perKill: Number(tournament.perKill) || 0 });
  } catch (e) {
    res.status(500).json({ error: 'Failed to preview prizes' });
  }
});

// ——— Custom match results ———
router.get('/admin/:id/results/custom-match', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const teams = await Team.find({ tournamentId: tournament._id, status: 'registered' }).lean();
    const members = await TeamMember.find({ tournamentId: tournament._id })
      .populate('userId', 'username')
      .lean();

    const saved = await CustomMatchResult.findOne({ tournamentId: tournament._id })
      .populate('winnerTeamId')
      .populate('runnerUpTeamId')
      .populate('mvpUserId', 'username');

    const prizeDistribution = await PrizeDistribution.findOne({ tournamentId: tournament._id }).lean();

    res.json({
      teams: teams.map((t) => ({
        ...t,
        members: members.filter((m) => String(m.teamId) === String(t._id)),
      })),
      result: saved,
      prizeDistribution,
      status: lifecycle.getEffectiveStatus(tournament),
    });
  } catch (e) {
    res.status(500).json({ error: 'Failed to load Clash Squad data' });
  }
});

router.post('/admin/:id/results/custom-match', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const status = lifecycle.getEffectiveStatus(tournament);
    if (lifecycle.areResultsPublished(tournament)) {
      return res.status(400).json({ error: 'Tournament is read-only after results are published' });
    }
    if (status !== 'completed') {
      return res.status(400).json({
        error: 'Mark the tournament as Completed before entering or publishing results',
      });
    }

    const teams = await Team.find({ tournamentId: tournament._id, status: 'registered' });
    if (teams.length < 1) {
      return res.status(400).json({ error: 'No registered teams found' });
    }

    const teamIds = teams.map((t) => t._id);
    let { winnerTeamId, runnerUpTeamId, mvpUserId, winnerPrize, runnerUpPrize, publish } = req.body;

    // Auto runner-up = the other registered team
    if (winnerTeamId && !runnerUpTeamId) {
      const other = teams.find((t) => String(t._id) !== String(winnerTeamId));
      if (other) runnerUpTeamId = other._id;
    }

    // Auto MVP = winning team captain when not provided
    if (winnerTeamId && !mvpUserId) {
      const winnerTeam = teams.find((t) => String(t._id) === String(winnerTeamId));
      if (winnerTeam?.captainUserId) mvpUserId = winnerTeam.captainUserId;
    }

    // Custom Match: winner gets 100% of configured prize; loser gets ₹0
    const prizeDistribution = await PrizeDistribution.findOne({ tournamentId: tournament._id }).lean();
    const resolvedWinnerPrize =
      Number(winnerPrize) > 0
        ? Number(winnerPrize)
        : Number(prizeDistribution?.winnerPrize) ||
          Number(tournament.prizes?.first) ||
          Number(tournament.prizePool) ||
          0;
    const resolvedRunnerUpPrize = 0;

    const payload = {
      winnerTeamId,
      runnerUpTeamId,
      mvpUserId,
      winnerPrize: resolvedWinnerPrize,
      runnerUpPrize: resolvedRunnerUpPrize,
    };
    const v = lifecycle.validateCustomResult(payload, teamIds);
    if (!v.ok) return res.status(400).json({ error: v.error });

    if (!runnerUpTeamId) {
      return res.status(400).json({ error: 'Runner-up team is required (need 2 registered teams)' });
    }

    const doc = await CustomMatchResult.findOneAndUpdate(
      { tournamentId: tournament._id },
      {
        tournamentId: tournament._id,
        winnerTeamId,
        runnerUpTeamId,
        mvpUserId: mvpUserId || undefined,
        winnerPrize: resolvedWinnerPrize,
        runnerUpPrize: resolvedRunnerUpPrize,
        updatedAt: new Date(),
      },
      { upsert: true, new: true }
    );

    // Keep PrizeDistribution in sync (winner only)
    await PrizeDistribution.findOneAndUpdate(
      { tournamentId: tournament._id },
      {
        tournamentId: tournament._id,
        tournamentType: 'custom_match',
        rankTiers: [],
        winnerPrize: resolvedWinnerPrize,
        runnerUpPrize: 0,
        updatedAt: new Date(),
      },
      { upsert: true, new: true }
    );

    if (publish) {
      const marked = lifecycle.markResultsPublished(tournament);
      if (!marked.ok) return res.status(400).json({ error: marked.error });
      await tournament.save();

      // Winner payout via controlled lifecycle (wallet credit; gateway is ZapUPI for deposits/join)
      let winnerPrizeCredited = 0;
      if (resolvedWinnerPrize > 0) {
        const winnerTeam = teams.find((t) => String(t._id) === String(winnerTeamId));
        const captainId = winnerTeam?.captainUserId;
        if (captainId) {
          const captain = await User.findById(captainId).select('username');
          await winnerPayoutService.ensurePayoutRecords([
            {
              tournamentId: tournament._id,
              userId: captainId,
              resultId: doc._id,
              resultModel: 'CustomMatchResult',
              amount: resolvedWinnerPrize,
              usernameSnapshot: captain?.username || '',
              description: `Clash Squad winner prize — ${tournament.name}`,
            },
          ]);
          const credit = await winnerPayoutService.autoCreditPendingForTournament(tournament._id, {
            tournamentName: tournament.name,
          });
          winnerPrizeCredited = credit.credited > 0 ? resolvedWinnerPrize : 0;
          if (credit.credited > 0) {
            doc.prizeCredited = true;
            await doc.save();
          }
        }
      }

      try {
        const winnerTeam = teams.find((t) => String(t._id) === String(winnerTeamId));
        const captainId = winnerTeam?.captainUserId;
        const winnerAmounts = {};
        const winnerUserIds = [];
        if (captainId && resolvedWinnerPrize > 0) {
          winnerUserIds.push(String(captainId));
          winnerAmounts[String(captainId)] = resolvedWinnerPrize;
        }
        await notifyResultsPublished(tournament, { winnerUserIds, winnerAmounts });
      } catch (notifyErr) {
        console.error('custom results notify:', notifyErr.message);
      }

      return res.json({
        message: 'Results published successfully',
        result: doc,
        status: 'completed',
        resultsPublished: true,
        winnerPrizeCredited,
        autoPaymentEnabled: tournament.autoPaymentEnabled !== false,
        controlWindow: winnerPayoutService.getControlWindow(tournament),
      });
    }

    res.json({ message: 'Clash Squad results saved', result: doc, status, resultsPublished: false });
  } catch (e) {
    console.error('save custom:', e);
    res.status(500).json({ error: e.message || 'Failed to save Clash Squad results' });
  }
});

// ——— Public results (new) ———
router.get('/:id/results', async (req, res) => {
  try {
    const tournament = await Tournament.findById(req.params.id).populate('gameMode', 'name').lean();
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const status = lifecycle.getEffectiveStatus(tournament);
    const published = lifecycle.areResultsPublished(tournament);

    if (status === 'completed' && !published) {
      return res.json({
        tournament: {
          _id: tournament._id,
          name: tournament.name,
          category: tournament.category,
          status,
          resultsPublished: false,
        },
        resultPending: true,
        message: 'Result Not Published Yet',
        tournamentType: lifecycle.getTournamentType(tournament),
      });
    }
    if (status !== 'completed' || !published) {
      return res.status(403).json({ error: 'Results are not published yet', resultPending: true });
    }

    const type = lifecycle.getTournamentType(tournament);

    if (type === 'battle_royale') {
      const isTeamMode = lifecycle.usesTeamRegistration(tournament);

      if (isTeamMode) {
        const teamRows = await BattleRoyaleTeamResult.find({ tournamentId: req.params.id })
          .populate('teamId')
          .sort({ position: 1 })
          .lean();
        const members = await TeamMember.find({ tournamentId: req.params.id })
          .populate('userId', 'username')
          .lean();

        const leaderboard = teamRows.map((r) => {
          const team = r.teamId;
          const teamMembers = members.filter(
            (m) => String(m.teamId) === String(team?._id || r.teamId)
          );
          return {
            rank: r.position,
            position: r.position,
            teamId: team?._id || r.teamId,
            teamName: team?.name || 'Team',
            players: team?.players || [],
            members: teamMembers.map((m) => ({
              userId: m.userId?._id || m.userId,
              username: m.userId?.username || m.gamingUsername,
            })),
            kills: r.teamKills,
            placementPrize: r.placementPrize,
            killReward: r.killReward,
            prize: r.totalPrize,
            totalReward: r.totalPrize,
          };
        });

        const winner = leaderboard.find((e) => e.rank === 1) || null;

        return res.json({
          tournament: {
            _id: tournament._id,
            name: tournament.name,
            category: tournament.category,
            mode: tournament.mode,
            status,
          },
          tournamentType: 'battle_royale',
          isBattleRoyale: true,
          isTeamMode: true,
          winner,
          leaderboard,
        });
      }

      const results = await BattleRoyaleResult.find({ tournamentId: req.params.id })
        .populate('userId', 'username')
        .sort({ position: 1 })
        .lean();

      const leaderboard = results.map((r) => ({
        rank: r.position,
        position: r.position,
        userId: r.userId?._id || r.userId,
        username: r.userId?.username,
        gamingID: r.gamingUsername,
        gamingUID: r.gamingUID,
        kills: r.kills,
        prize: r.prize,
        totalReward: r.prize,
      }));

      const winner = leaderboard.find((e) => e.rank === 1) || null;

      return res.json({
        tournament: {
          _id: tournament._id,
          name: tournament.name,
          category: tournament.category,
          status,
        },
        tournamentType: 'battle_royale',
        isBattleRoyale: true,
        isTeamMode: false,
        winner,
        leaderboard,
      });
    }

    const custom = await CustomMatchResult.findOne({ tournamentId: req.params.id })
      .populate('winnerTeamId')
      .populate('runnerUpTeamId')
      .populate('mvpUserId', 'username')
      .lean();

    if (!custom) {
      return res.status(404).json({ error: 'Results not found' });
    }

    const mvpMember = await TeamMember.findOne({
      tournamentId: req.params.id,
      userId: custom.mvpUserId,
    }).lean();

    return res.json({
      tournament: {
        _id: tournament._id,
        name: tournament.name,
        category: tournament.category,
        status,
      },
      tournamentType: 'custom_match',
      isBattleRoyale: false,
      customMatch: {
        winnerTeam: custom.winnerTeamId,
        runnerUpTeam: custom.runnerUpTeamId,
        mvp: {
          userId: custom.mvpUserId,
          username: custom.mvpUserId?.username,
          gamingUsername: mvpMember?.gamingUsername,
          gamingUID: mvpMember?.gamingUID,
        },
        winnerPrize: custom.winnerPrize,
        runnerUpPrize: 0,
      },
    });
  } catch (e) {
    console.error('public results:', e);
    res.status(500).json({ error: 'Failed to fetch results' });
  }
});

// ——— Export ———
router.get('/admin/:id/results/export', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;

    const tournament = await Tournament.findById(req.params.id).lean();
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    const type = lifecycle.getTournamentType(tournament);

    if (type === 'battle_royale') {
      const rows = await BattleRoyaleResult.find({ tournamentId: req.params.id })
        .populate('userId', 'username email')
        .sort({ position: 1 });
      return res.json({
        tournamentName: tournament.name,
        type: 'battle_royale',
        rows: rows.map((r) => ({
          rank: r.position,
          player: r.gamingUsername || r.userId?.username,
          kills: r.kills,
          prize: r.prize,
        })),
      });
    }

    const custom = await CustomMatchResult.findOne({ tournamentId: req.params.id })
      .populate('winnerTeamId', 'name')
      .populate('runnerUpTeamId', 'name')
      .populate('mvpUserId', 'username');

    res.json({
      tournamentName: tournament.name,
      type: 'custom_match',
      custom,
    });
  } catch (e) {
    res.status(500).json({ error: 'Export failed' });
  }
});

// Register team — Team Name + Side (custom) + Game ID + UID for every player
router.post('/:id/register-team', authMiddleware, async (req, res) => {
  try {
    const user = await User.findById(req.userId);
    if (!user) return res.status(404).json({ error: 'User not found' });
    if (user.role === 'admin') {
      return res.status(403).json({ error: 'Admins cannot join as participants' });
    }
    if (user.status !== 'active') {
      return res.status(403).json({ error: 'Account is not active' });
    }

    const tournament = await Tournament.findById(req.params.id).populate('matchType');
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    if (!lifecycle.isCustomMatch(tournament) && !lifecycle.usesTeamRegistration(tournament)) {
      return res.status(400).json({
        error: 'Team registration is for Clash Squad or Duo/Squad Battle Royale only. Solo uses slot booking.',
      });
    }

    const status = lifecycle.getEffectiveStatus(tournament);
    if (!lifecycle.canJoin(status)) {
      return res.status(400).json({ error: 'Registration is not open' });
    }

    const isCustom = lifecycle.isCustomMatch(tournament);
    const structure = lifecycle.getMatchStructure(tournament);
    const { teamName, teamSide, players, slotNumber: slotNumberRaw } = req.body;
    const sideRaw = String(teamSide || req.body.side || '')
      .trim()
      .toUpperCase()
      .replace('TEAM ', '');
    const side = sideRaw === 'A' || sideRaw === 'B' ? sideRaw : null;

    if (!teamName || !String(teamName).trim()) {
      return res.status(400).json({ error: 'Team name is required' });
    }
    if (isCustom && !side) {
      return res.status(400).json({ error: 'Team side must be Team A or Team B' });
    }

    const requiredPlayers = lifecycle.getPlayersPerTeam(tournament.mode);
    if (!Array.isArray(players) || players.length !== requiredPlayers) {
      const modeLabel = String(tournament.mode || 'solo').toLowerCase();
      return res.status(400).json({
        error:
          modeLabel === 'squad'
            ? 'Squad requires exactly 4 players (Game ID + UID each)'
            : modeLabel === 'duo'
              ? 'Duo requires exactly 2 players (Game ID + UID each)'
              : 'Solo requires exactly 1 player (Game ID + UID)',
        requiredPlayers,
      });
    }

    const normalizedPlayers = players.map((p, idx) => {
      const name = String(typeof p === 'string' ? p : p?.name || p?.gamingUsername || '').trim();
      const gamingUID = String(
        typeof p === 'object' ? p?.gamingUID || p?.uid || p?.gameUID || '' : ''
      ).trim();
      return { name, gamingUID, index: idx };
    });

    const missingName = normalizedPlayers.find((p) => !p.name || p.name.length < 3);
    if (missingName) {
      return res.status(400).json({
        error: `Player ${missingName.index + 1}: Game ID (in-game name) is required (min 3 characters)`,
      });
    }
    const missingUid = normalizedPlayers.find((p) => !p.gamingUID || p.gamingUID.length < 3);
    if (missingUid) {
      return res.status(400).json({
        error: `Player ${missingUid.index + 1}: Game UID is required (min 3 characters)`,
      });
    }

    const teamCount = await Team.countDocuments({ tournamentId: tournament._id, status: 'registered' });
    const maxTeams = isCustom
      ? tournament.maxTeams || 2
      : tournament.maxTeams ||
        Math.floor((tournament.maxParticipants || 50) / requiredPlayers);
    if (teamCount >= maxTeams) {
      return res.status(400).json({
        error: isCustom ? 'Match is full — both teams registered' : 'All team slots are full',
        isFull: true,
      });
    }

    if (isCustom && side) {
      const sideTaken = await Team.findOne({
        tournamentId: tournament._id,
        side,
        status: 'registered',
      });
      if (sideTaken) {
        return res.status(400).json({ error: `Team ${side} is already registered` });
      }
    }

    let slotNumber = null;
    if (!isCustom && structure.usesTeamRegistration) {
      slotNumber = Number(slotNumberRaw);
      if (!slotNumber || slotNumber < 1 || slotNumber > structure.totalSlots) {
        const taken = await Team.find({ tournamentId: tournament._id, status: 'registered' }).select('slotNumber');
        const used = new Set(taken.map((t) => Number(t.slotNumber)).filter(Boolean));
        for (let i = 1; i <= structure.totalSlots; i += 1) {
          if (!used.has(i)) {
            slotNumber = i;
            break;
          }
        }
      }
      if (!slotNumber) {
        return res.status(400).json({ error: 'All slots are full' });
      }
      const slotTaken = await Team.findOne({
        tournamentId: tournament._id,
        slotNumber,
        status: 'registered',
      });
      if (slotTaken) {
        return res.status(400).json({ error: `Slot ${slotNumber} is already booked` });
      }
    }

    const nameTaken = await Team.findOne({
      tournamentId: tournament._id,
      status: 'registered',
      name: { $regex: `^${String(teamName).trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, $options: 'i' },
    });
    if (nameTaken) {
      return res.status(400).json({ error: 'A team with this name is already registered in this match' });
    }

    const existingMember = await TeamMember.findOne({
      tournamentId: tournament._id,
      userId: req.userId,
    });
    const existingParticipant = await TournamentParticipant.findOne({
      tournamentId: tournament._id,
      userId: req.userId,
    });
    if (existingMember || existingParticipant) {
      return res.status(400).json({ error: 'You are already registered in this tournament' });
    }

    // Entry fee is per player; captain pays fee × roster size for duo/squad/clash
    const charge = lifecycle.resolveEntryCharge(tournament);
    const { bonusUsed, realMoneyRequired } = getEntryPaymentSplit(user, charge.totalAmount);
    if (user.wallet.balance < realMoneyRequired) {
      return res.status(400).json({
        error: `Insufficient real balance! Team entry is ₹${charge.totalAmount} (₹${charge.feePerPlayer} × ${charge.playersCharged} players; need ₹${realMoneyRequired} real; can use ₹${bonusUsed} bonus). Current: ₹${user.wallet.balance}.`,
      });
    }

    const teamPayload = {
      tournamentId: tournament._id,
      name: String(teamName).trim(),
      players: normalizedPlayers.map(({ name, gamingUID }) => ({ name, gamingUID })),
      captainUserId: req.userId,
    };
    if (isCustom && side) teamPayload.side = side;
    if (slotNumber) teamPayload.slotNumber = slotNumber;

    const team = await Team.create(teamPayload);

    await TeamMember.create({
      tournamentId: tournament._id,
      teamId: team._id,
      userId: req.userId,
      gamingUsername: normalizedPlayers[0].name,
      gamingUID: normalizedPlayers[0].gamingUID,
      role: 'captain',
    });

    user.wallet.balance -= realMoneyRequired;
    user.wallet.bonusBalance = Math.max((user.wallet.bonusBalance || 0) - bonusUsed, 0);
    user.wallet.bonusUsed = (user.wallet.bonusUsed || 0) + bonusUsed;
    user.tournament.participatedCount = (user.tournament.participatedCount || 0) + 1;
    await user.save();

    const entryLabel = isCustom ? 'Clash Squad' : 'Battle Royale';
    const sideLabel = side ? ` / Team ${side}` : '';

    await WalletTransaction.create({
      userId: req.userId,
      type: 'tournament_entry',
      amount: charge.totalAmount,
      tournamentId: tournament._id,
      description: `${entryLabel} team entry (₹${charge.feePerPlayer}/player × ${charge.playersCharged} = ₹${charge.totalAmount}) — ${tournament.name}${sideLabel}`,
      status: 'completed',
    });

    await notifyTournamentJoined(req.userId, tournament).catch(() => {});

    tournament.currentParticipants = (teamCount + 1) * requiredPlayers;
    if (!tournament.registeredPlayers.some((id) => String(id) === String(req.userId))) {
      tournament.registeredPlayers.push(req.userId);
    }
    await tournament.save();

    res.status(201).json({
      message:
        charge.playersCharged > 1
          ? `Team registered. Charged ₹${charge.totalAmount} (₹${charge.feePerPlayer} × ${charge.playersCharged} players).`
          : 'Team registered successfully.',
      team: {
        _id: team._id,
        name: team.name,
        side: team.side,
        players: team.players,
      },
      payment: {
        entryFee: charge.feePerPlayer,
        feePerPlayer: charge.feePerPlayer,
        playersCharged: charge.playersCharged,
        totalAmount: charge.totalAmount,
        chargedPer: charge.chargedPer,
        bonusUsed,
        realMoneyRequired,
      },
    });
  } catch (e) {
    console.error('register-team:', e);
    if (e.code === 11000) {
      return res.status(400).json({ error: 'Team name or side is already taken for this match' });
    }
    res.status(500).json({ error: e.message || 'Failed to register team' });
  }
});

// ——— Winner payout control (10-minute wait then auto-credit) ———

router.get('/admin/:id/payouts', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    const data = await winnerPayoutService.listTournamentPayouts(req.params.id);
    if (!data) return res.status(404).json({ error: 'Tournament not found' });
    res.json(data);
  } catch (e) {
    console.error('list payouts:', e);
    res.status(500).json({ error: e.message || 'Failed to load payouts' });
  }
});

router.put('/admin/:id/auto-payment', authMiddleware, async (req, res) => {
  try {
    if (!(await requireAdmin(req, res))) return;
    const enabled = !!req.body?.enabled;
    const tournament = await winnerPayoutService.setAutoPayment(req.params.id, enabled);
    if (!tournament) return res.status(404).json({ error: 'Tournament not found' });

    res.json({
      message: `Auto Payment ${enabled ? 'ON' : 'OFF'}`,
      autoPaymentEnabled: tournament.autoPaymentEnabled !== false,
      note: enabled
        ? 'Due PENDING payouts will credit automatically after the 10-minute wait.'
        : 'PENDING payouts will not auto-credit until Auto Payment is turned ON.',
      controlWindow: winnerPayoutService.getControlWindow(tournament),
    });
  } catch (e) {
    console.error('auto-payment:', e);
    res.status(500).json({ error: e.message || 'Failed to update auto payment' });
  }
});

router.post('/admin/:id/cancel', authMiddleware, async (req, res) => {
  try {
    const admin = await requireAdmin(req, res);
    if (!admin) return;
    const { cancelTournamentWithRefunds } = require('../services/tournamentRefundService');
    const result = await cancelTournamentWithRefunds(
      req.params.id,
      admin._id,
      req.body?.reason || 'Cancelled by admin'
    );
    res.json({
      message: 'Tournament cancelled. Entry fees refunded where applicable.',
      ...result,
    });
  } catch (e) {
    res.status(e.status || 500).json({ error: e.message, code: e.code });
  }
});

router.post('/admin/payouts/:payoutId/stop', authMiddleware, async (req, res) => {
  try {
    const admin = await requireAdmin(req, res);
    if (!admin) return;
    if (!req.body?.reason) {
      return res.status(400).json({ error: 'Reason is required' });
    }
    const payout = await winnerPayoutService.stopPendingPayout(
      req.params.payoutId,
      admin._id,
      req.body.reason
    );
    res.json({ message: 'Payout cancelled. No wallet credit will be issued.', payout });
  } catch (e) {
    res.status(e.status || 500).json({ error: e.message, code: e.code, payout: e.payout });
  }
});

router.post('/admin/payouts/:payoutId/block', authMiddleware, async (req, res) => {
  try {
    const admin = await requireAdmin(req, res);
    if (!admin) return;
    if (!req.body?.reason) {
      return res.status(400).json({ error: 'Reason is required' });
    }
    const payout = await winnerPayoutService.blockPayout(
      req.params.payoutId,
      admin._id,
      req.body.reason
    );
    res.json({ message: 'Payout blocked', payout });
  } catch (e) {
    res.status(e.status || 500).json({ error: e.message, code: e.code });
  }
});

router.post('/admin/payouts/:payoutId/reject', authMiddleware, async (req, res) => {
  try {
    const admin = await requireAdmin(req, res);
    if (!admin) return;
    if (!req.body?.reason) {
      return res.status(400).json({ error: 'Reason is required' });
    }
    const payout = await winnerPayoutService.rejectPayout(
      req.params.payoutId,
      admin._id,
      req.body.reason
    );
    res.json({ message: 'Payout rejected', payout });
  } catch (e) {
    res.status(e.status || 500).json({ error: e.message, code: e.code });
  }
});

router.post('/admin/payouts/:payoutId/reverse', authMiddleware, async (req, res) => {
  try {
    const admin = await requireAdmin(req, res);
    if (!admin) return;
    const result = await winnerPayoutService.reversePaidPayout(
      req.params.payoutId,
      admin._id,
      req.body?.reason || 'Reversed by admin'
    );
    res.json({ message: 'Payout reversed successfully', ...result });
  } catch (e) {
    res.status(e.status || 500).json({
      error: e.message || 'Failed to reverse payout',
      code: e.code,
      details: e.details,
    });
  }
});

module.exports = router;
