const mongoose = require('mongoose');

const tournamentSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  description: String,
  bannerImage: {
    type: String,
    default: '',
  },
  bannerTitle: {
    type: String,
    default: '',
    trim: true,
  },
  matchNumber: {
    type: Number,
    unique: true,
    sparse: true,
  },
  game: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Game',
    required: true,
  },
  gameMode: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'GameMode',
    required: true,
  },
  mode: {
    type: String,
    enum: ['solo', 'duo', 'squad'],
    default: 'solo',
  },
  category: {
    type: String,
    enum: ['battle_royale', 'custom', 'custom_match'],
    default: 'battle_royale',
  },
  /** Primary lifecycle: draft → upcoming → ongoing → completed */
  lifecycleStatus: {
    type: String,
    enum: ['draft', 'upcoming', 'ongoing', 'completed', 'result_published', 'cancelled'],
    default: 'draft',
  },
  maxTeams: {
    type: Number,
    default: 2,
  },
  rewardType: {
    type: String,
    enum: ['per_kill', 'survival', 'hybrid'],
    default: 'per_kill',
  },
  resultsPublished: {
    type: Boolean,
    default: false,
  },
  resultsPublishedAt: {
    type: Date,
  },
  /** When true, PENDING winner payouts auto-credit on publish (TEST wallet). */
  autoPaymentEnabled: {
    type: Boolean,
    default: true,
  },
  map: {
    type: String,
    default: 'Bermuda',
  },
  rules: [{
    type: String,
  }],
  entryFee: {
    type: Number,
    required: true,
  },
  prizePool: {
    type: Number,
    default: 0,
  },
  perKill: {
    type: Number,
    default: 0,
  },
  maxParticipants: {
    type: Number,
    required: true,
  },
  currentParticipants: {
    type: Number,
    default: 0,
  },
  registeredPlayers: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  }],
  status: {
    type: String,
    enum: [
      'draft', 'upcoming', 'ongoing', 'completed', 'result_published', 'cancelled',
      'incoming', 'live', 'locked',
    ],
    default: 'draft',
  },
  statusOverride: {
    type: Boolean,
    default: false,
  },
  locked: {
    type: Boolean,
    default: false,
  },
  lockedAt: {
    type: Date,
  },
  startDate: {
    type: Date,
    required: true,
  },
  endDate: Date,
  minimumBalance: {
    type: Number,
    default: 0,
  },
  roomId: String, // Game room ID
  roomPassword: String, // Game room password (encrypted)
  showRoomCredentials: {
    type: Boolean,
    default: false,
  },
  roomCredentialsSharedAt: {
    type: Date,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  prizes: {
    first: Number,
    second: Number,
    third: Number,
  },
  winners: [{
    userId: mongoose.Schema.Types.ObjectId,
    position: Number,
    reward: Number,
  }],
  // Slot booking system (50 fixed slots)
  slots: [{
    slotNumber: {
      type: Number,
      min: 1,
      max: 50,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    gamingUsername: String,
    gamingUID: String,
    bookedAt: Date,
    isBooked: {
      type: Boolean,
      default: false,
    },
  }],
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
  /** Set only on tournaments generated from a Daily Auto Match master. */
  isAutoGenerated: {
    type: Boolean,
    default: false,
  },
  autoMatchId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'DailyAutoMatch',
    default: undefined,
  },
  /** Calendar date in Asia/Kolkata as YYYY-MM-DD. Independent snapshot of that day's match. */
  generatedDate: {
    type: String,
    default: undefined,
  },
});

tournamentSchema.index({ lifecycleStatus: 1, startDate: -1 });
tournamentSchema.index({ status: 1, startDate: -1 });
tournamentSchema.index({ gameMode: 1, lifecycleStatus: 1 });
tournamentSchema.index({ category: 1, mode: 1 });
tournamentSchema.index({ name: 1 });
tournamentSchema.index({ createdAt: -1 });
tournamentSchema.index({ autoMatchId: 1, generatedDate: -1 });
tournamentSchema.index(
  { autoMatchId: 1, generatedDate: 1 },
  {
    unique: true,
    name: 'uniq_autoMatch_per_day',
    partialFilterExpression: {
      isAutoGenerated: true,
      autoMatchId: { $exists: true, $type: 'objectId' },
      generatedDate: { $exists: true, $type: 'string' },
    },
  }
);

module.exports = mongoose.model('Tournament', tournamentSchema);
